### ISSUE TITLE
Incorrect link for library

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#111]
From the forum: 
> I am now getting a 404 error when trrying to download the platform package. Apparently this URL is incorrect:

https://github.com/bigjosh/Move38-Arduino-Platform/releases/download/1.3.1/Move38-Arduino-Platform-main.zip

I get a 404 when trying to download it manually.

Apparently the right link is:

https://github.com/bigjosh/Move38-Arduino-Platform/releases/download/1.3.1/Move38-Arduino-Platform.zip

(no “main” in the zip file name).

**Comment by bigjosh** [comment]
I think already fixed!

**Comment by jbobrow** [comment]
Thanks Josh! I was too slow. All caught up now :)
