### ISSUE TITLE
Board Manager URL

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#4]
`https://bigjosh.github.io//package_index.json` tested with Arduino 1.8.0 and 1.8.4 doesn't add the Move38 Blinks hardware type to the board manager. Looks like the github.io page isn't published

**Comment by leppert** [comment]
@bigjosh Any ideas?

**Comment by bigjosh** [comment]
Board manager stuff is not rolled out yet, you have to do the local install.

**Comment by jbobrow** [comment]
Greg’s up an running with the latest, looks like all of the examples are not working in the Dev branch. Something we’re missing?

––
www.move38.com | www.jonathanbobrow.com | www.bitwise-design.com

**Comment by leppert** [comment]
```
Arduino: 1.8.5 (Mac OS X), Board: "Blinks Tile"

/var/folders/h5/5rty7brs56l06twmrxkw13s40000gn/T/arduino_modified_sketch_380738/HSBColorWheel.ino:1:19: fatal error: blink.h: No such file or directory
 #include "blink.h"
                   ^
compilation terminated.
exit status 1
Error compiling for board Blinks Tile.
```

**Comment by bigjosh** [comment]
Giving up on board manager integration for now. Current system works fine and avoids so many Arduino problems. Maybe someday will will make a portable library stub that comes over the Arduino board manager.
