### ISSUE TITLE
Should hasWoke() return true or false on the first check after start up?

### ISSUE THREAD

**Issue by bigjosh** [bigjosh/Move38-Arduino-Platform#58]
Current behavior is "no", but if we make it yes then games that want to restart on both power up and waking will be able to do a single check to cover both. Games that do not care, can call `hasWoke()` in `setup()`.

**Comment by jbobrow** [comment]
trying to think of the use cases. It sounds like the current method is fine

**Comment by bigjosh** [comment]
Yep, kind of a philosophical question since doesn't seem like games need to be too sophisticated on this stuff to seem to work fine.
