### ISSUE TITLE
Individual Gamma table for RGB

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#59]
White at the low end is heavily skewed in the Blue direction, having individual gamma tables seems appropriate for our hardware but takes up another 64 bytes, if I understand this correctly.

**Comment by bigjosh** [comment]
Correct - right now we have a single table of 32 bytes that lives in the bootloader area. All three R,G,B currently use the same table. We could break that out into individual tables for each color, or one table for R & G and another for just B. Or if there is just one or two RGB values of white that look off, we could special case those out.

**Comment by bigjosh** [comment]
Not gonna happen - no room. We can possibly slightly tweak individual values if anything is really ugly, but looks pretty smooth to my eye now!
