### ISSUE TITLE
Make program long hold start after 4000ms and remain in program mode for 2000ms

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#70]

**Comment by bigjosh** [comment]
Program send mode starts after button hold for 4000ms if blink alone.
Enter sleep after 6000ms hold down.

**Comment by bigjosh** [comment]
Replaces #62

**Comment by jbobrow** [comment]
Opening a new issue for button timing (created prototype to test timing and found good lengths)

**Comment by bigjosh** [comment]
This is now implemented in `/dev` branch.

**Comment by jbobrow** [comment]
Just confirming that the timing matches the timing issue. 1200ms for long press, 3000ms program press, 6000ms sleeper hold

**Comment by bigjosh** [comment]
Currently 1200ms, 4000ms, and 6000ms in /dev. Try it and LMK if you want me to change back to 3000ms to enter programming mode.
