### ISSUE TITLE
Animation on Wake

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#72]
Allow for a half second white spiral w/ trail on wake

**Comment by jbobrow** [comment]
30ms on each LED with white increasing from 0 - 31

**Comment by bigjosh** [comment]
So with [~16 steps](https://www.google.com/search?q=0.5s+%2F+30ms&oq=0.5s+%2F+30ms&aqs=chrome..69i57j6.1998j0j9&sourceid=chrome&ie=UTF-8)?

**Comment by jbobrow** [comment]
I should just try it out, and send the exact description

**Comment by jbobrow** [comment]
Wake and sleep animations are detailed in issue #73, that is the one to follow :)

**Comment by jbobrow** [comment]
Much better now, however, the animation should be white for the wake. The travel from Tile to tile is much quicker than the sleep propagation, matching would feel the best, i.e. slowing the tile to tile on wake, however, it is not worth losing memory for such an update.

**Comment by jbobrow** [comment]
@bigjosh just another ping on the animation for wake to be white instead the current blue
