### ISSUE TITLE
Can't find onWake()

### ISSUE THREAD

**Issue by jbobrow** [bigjosh/Move38-Arduino-Platform#89]

**Comment by jbobrow** [comment]
Would like to handle some situations onWake of a blink and couldn't find a flag in the API that allowed for this (most likely just missing it)

**Comment by bigjosh** [comment]
[`hasWoken()`](https://github.com/bigjosh/Move38-Arduino-Platform/blob/dev/cores/blinklib/blinklib.h#L346)

...but I am warning you that the semantics are mushy. [We never pinned down](https://github.com/bigjosh/Move38-Arduino-Platform/issues/58) things like is first power up after battery insert a wake? Is starting up after a successful download a wake? Several others, I think no right answers but should at least be thoughtful and coherent - which it is not right now.

**Comment by bigjosh** [comment]
Keep in mind that this function is part of blinklib so each game will always see the same semantics it was compiled against, so we can refine semantics any time and new games get the benefit.
